using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.Extensions.DependencyInjection;
using Open.IdentityServer.EntityFramework.DbContexts;
using Open.IdentityServer.EntityFramework.Mappers;
using Open.IdentityServer.Models;
using Quorum.Backend.AdminUI.Models;

namespace Quorum.Backend.AdminUI.Data;

public static class SeedData
{
    private static async Task EnsureTablesCreatedAsync(DbContext context)
    {
        var databaseCreator = context.Database.GetService<IDatabaseCreator>() as IRelationalDatabaseCreator;
        if (databaseCreator != null)
        {
            if (!await databaseCreator.ExistsAsync())
            {
                await databaseCreator.CreateAsync();
            }
            try
            {
                await databaseCreator.CreateTablesAsync();
            }
            catch
            {
                // Baza już częściowo istniała (np. starsza wersja schema).
                // Dzielimy wygenerowany skrypt na pojedyncze instrukcje DDL, aby utworzyć brakujące tabele.
                try
                {
                    var script = databaseCreator.GenerateCreateScript();
                    var statements = script.Split(new[] { ";\r\n", ";\n", ";\r", "\r\nGO", "\nGO" }, StringSplitOptions.RemoveEmptyEntries);
                    foreach (var rawStatement in statements)
                    {
                        var statement = rawStatement.Trim();
                        if (!string.IsNullOrWhiteSpace(statement))
                        {
                            try
                            {
                                await context.Database.ExecuteSqlRawAsync(statement);
                            }
                            catch
                            {
                                // Ignorujemy błędy dla tabel i indeksów, które już istnieją
                            }
                        }
                    }
                }
                catch
                {
                    // W razie błędu parsera przechodzimy do jawnych fallbacków
                }
            }
        }

        // Dodatkowe, dedykowane zabezpieczenie dla tabel ApplicationDbContext (GatewayRoutes, FederationProviders)
        if (context is ApplicationDbContext appDb)
        {
            await EnsureApplicationTablesDirectlyAsync(appDb);
        }
    }

    private static async Task EnsureApplicationTablesDirectlyAsync(ApplicationDbContext appDb)
    {
        var provider = appDb.Database.ProviderName ?? string.Empty;

        // 1. Zapewnienie istnienia tabeli FederationProviders
        try
        {
            _ = await appDb.FederationProviders.AnyAsync();
        }
        catch
        {
            try
            {
                if (provider.Contains("Sqlite", StringComparison.OrdinalIgnoreCase))
                {
                    var sql = @"
CREATE TABLE IF NOT EXISTS ""FederationProviders"" (
    ""Id"" INTEGER NOT NULL CONSTRAINT ""PK_FederationProviders"" PRIMARY KEY AUTOINCREMENT,
    ""Scheme"" TEXT NOT NULL,
    ""DisplayName"" TEXT NOT NULL,
    ""Authority"" TEXT NOT NULL,
    ""ClientId"" TEXT NOT NULL,
    ""ClientSecret"" TEXT NULL,
    ""ResponseType"" TEXT NOT NULL,
    ""CallbackPath"" TEXT NOT NULL,
    ""SignedOutCallbackPath"" TEXT NULL,
    ""Scopes"" TEXT NOT NULL,
    ""GetClaimsFromUserInfoEndpoint"" INTEGER NOT NULL,
    ""SaveTokens"" INTEGER NOT NULL,
    ""Prompt"" TEXT NULL,
    ""MetadataAddress"" TEXT NULL,
    ""RequireHttpsMetadata"" INTEGER NOT NULL,
    ""TenantId"" TEXT NULL,
    ""AdditionalParametersJson"" TEXT NULL,
    ""IsEnabled"" INTEGER NOT NULL,
    ""CreatedAt"" TEXT NOT NULL,
    ""UpdatedAt"" TEXT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ""IX_FederationProviders_Scheme"" ON ""FederationProviders"" (""Scheme"");
";
                    await appDb.Database.ExecuteSqlRawAsync(sql);
                }
                else if (provider.Contains("Npgsql", StringComparison.OrdinalIgnoreCase) || provider.Contains("Postgre", StringComparison.OrdinalIgnoreCase))
                {
                    var sql = @"
CREATE TABLE IF NOT EXISTS ""FederationProviders"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""Scheme"" character varying(64) NOT NULL,
    ""DisplayName"" character varying(128) NOT NULL,
    ""Authority"" character varying(512) NOT NULL,
    ""ClientId"" character varying(256) NOT NULL,
    ""ClientSecret"" text,
    ""ResponseType"" character varying(64) NOT NULL,
    ""CallbackPath"" character varying(256) NOT NULL,
    ""SignedOutCallbackPath"" character varying(256),
    ""Scopes"" character varying(256) NOT NULL,
    ""GetClaimsFromUserInfoEndpoint"" boolean NOT NULL,
    ""SaveTokens"" boolean NOT NULL,
    ""Prompt"" character varying(64),
    ""MetadataAddress"" character varying(512),
    ""RequireHttpsMetadata"" boolean NOT NULL,
    ""TenantId"" character varying(128),
    ""AdditionalParametersJson"" text,
    ""IsEnabled"" boolean NOT NULL,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    ""UpdatedAt"" timestamp with time zone
);
CREATE UNIQUE INDEX IF NOT EXISTS ""IX_FederationProviders_Scheme"" ON ""FederationProviders"" (""Scheme"");
";
                    await appDb.Database.ExecuteSqlRawAsync(sql);
                }
                else if (provider.Contains("SqlServer", StringComparison.OrdinalIgnoreCase))
                {
                    var sql = @"
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'FederationProviders')
BEGIN
    CREATE TABLE [FederationProviders] (
        [Id] int IDENTITY(1,1) NOT NULL PRIMARY KEY,
        [Scheme] nvarchar(64) NOT NULL,
        [DisplayName] nvarchar(128) NOT NULL,
        [Authority] nvarchar(512) NOT NULL,
        [ClientId] nvarchar(256) NOT NULL,
        [ClientSecret] nvarchar(max) NULL,
        [ResponseType] nvarchar(64) NOT NULL,
        [CallbackPath] nvarchar(256) NOT NULL,
        [SignedOutCallbackPath] nvarchar(256) NULL,
        [Scopes] nvarchar(256) NOT NULL,
        [GetClaimsFromUserInfoEndpoint] bit NOT NULL,
        [SaveTokens] bit NOT NULL,
        [Prompt] nvarchar(64) NULL,
        [MetadataAddress] nvarchar(512) NULL,
        [RequireHttpsMetadata] bit NOT NULL,
        [TenantId] nvarchar(128) NULL,
        [AdditionalParametersJson] nvarchar(max) NULL,
        [IsEnabled] bit NOT NULL,
        [CreatedAt] datetime2 NOT NULL,
        [UpdatedAt] datetime2 NULL
    );
    CREATE UNIQUE INDEX [IX_FederationProviders_Scheme] ON [FederationProviders] ([Scheme]);
END
";
                    await appDb.Database.ExecuteSqlRawAsync(sql);
                }
            }
            catch
            {
                // Ignorujemy ewentualne błędy powtórnej próby
            }
        }

        // 2. Zapewnienie istnienia tabeli GatewayRoutes
        try
        {
            _ = await appDb.GatewayRoutes.AnyAsync();
        }
        catch
        {
            try
            {
                if (provider.Contains("Sqlite", StringComparison.OrdinalIgnoreCase))
                {
                    var sql = @"
CREATE TABLE IF NOT EXISTS ""GatewayRoutes"" (
    ""Id"" INTEGER NOT NULL CONSTRAINT ""PK_GatewayRoutes"" PRIMARY KEY AUTOINCREMENT,
    ""MatchPattern"" TEXT NOT NULL,
    ""RouteName"" TEXT NULL,
    ""Description"" TEXT NULL,
    ""Scheme"" TEXT NOT NULL DEFAULT 'https',
    ""AddressHost"" TEXT NOT NULL,
    ""AddressPort"" INTEGER NOT NULL DEFAULT 443,
    ""AddressBasePath"" TEXT NULL,
    ""AddressPath"" TEXT NULL,
    ""AddressQueryString"" TEXT NULL,
    ""Headers"" TEXT NULL,
    ""TimeoutSeconds"" INTEGER NOT NULL,
    ""HttpMethods"" TEXT NOT NULL DEFAULT 'ALL',
    ""AllowAnonymous"" INTEGER NOT NULL DEFAULT 0,
    ""RequiredScope"" INTEGER NOT NULL DEFAULT 0,
    ""ApiScopeId"" INTEGER NULL,
    ""ScopeName"" TEXT NULL,
    ""AuthenticationSchemes"" TEXT NULL DEFAULT 'Bearer',
    ""IsEnabled"" INTEGER NOT NULL DEFAULT 1,
    ""Priority"" INTEGER NOT NULL DEFAULT 0,
    ""EnableCaching"" INTEGER NOT NULL DEFAULT 0,
    ""ForwardOriginalHost"" INTEGER NOT NULL DEFAULT 1,
    ""CreatedAt"" TEXT NOT NULL,
    ""UpdatedAt"" TEXT NULL
);
CREATE INDEX IF NOT EXISTS ""IX_GatewayRoutes_MatchPattern"" ON ""GatewayRoutes"" (""MatchPattern"");
CREATE INDEX IF NOT EXISTS ""IX_GatewayRoutes_Priority"" ON ""GatewayRoutes"" (""Priority"");
CREATE INDEX IF NOT EXISTS ""IX_GatewayRoutes_IsEnabled"" ON ""GatewayRoutes"" (""IsEnabled"");
";
                    await appDb.Database.ExecuteSqlRawAsync(sql);
                }
                else if (provider.Contains("Npgsql", StringComparison.OrdinalIgnoreCase) || provider.Contains("Postgre", StringComparison.OrdinalIgnoreCase))
                {
                    var sql = @"
CREATE TABLE IF NOT EXISTS ""GatewayRoutes"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""MatchPattern"" character varying(255) NOT NULL,
    ""RouteName"" character varying(128),
    ""Description"" character varying(512),
    ""Scheme"" character varying(16) NOT NULL DEFAULT 'https',
    ""AddressHost"" character varying(255) NOT NULL,
    ""AddressPort"" integer NOT NULL DEFAULT 443,
    ""AddressBasePath"" character varying(255),
    ""AddressPath"" character varying(255),
    ""AddressQueryString"" character varying(500),
    ""Headers"" text,
    ""TimeoutSeconds"" integer NOT NULL,
    ""HttpMethods"" character varying(64) NOT NULL DEFAULT 'ALL',
    ""AllowAnonymous"" boolean NOT NULL DEFAULT FALSE,
    ""RequiredScope"" boolean NOT NULL DEFAULT FALSE,
    ""ApiScopeId"" integer,
    ""ScopeName"" character varying(200),
    ""AuthenticationSchemes"" character varying(255) DEFAULT 'Bearer',
    ""IsEnabled"" boolean NOT NULL DEFAULT TRUE,
    ""Priority"" integer NOT NULL DEFAULT 0,
    ""EnableCaching"" boolean NOT NULL DEFAULT FALSE,
    ""ForwardOriginalHost"" boolean NOT NULL DEFAULT TRUE,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    ""UpdatedAt"" timestamp with time zone
);
CREATE INDEX IF NOT EXISTS ""IX_GatewayRoutes_MatchPattern"" ON ""GatewayRoutes"" (""MatchPattern"");
CREATE INDEX IF NOT EXISTS ""IX_GatewayRoutes_Priority"" ON ""GatewayRoutes"" (""Priority"");
CREATE INDEX IF NOT EXISTS ""IX_GatewayRoutes_IsEnabled"" ON ""GatewayRoutes"" (""IsEnabled"");
";
                    await appDb.Database.ExecuteSqlRawAsync(sql);
                }
                else if (provider.Contains("SqlServer", StringComparison.OrdinalIgnoreCase))
                {
                    var sql = @"
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'GatewayRoutes')
BEGIN
    CREATE TABLE [GatewayRoutes] (
        [Id] int IDENTITY(1,1) NOT NULL PRIMARY KEY,
        [MatchPattern] nvarchar(255) NOT NULL,
        [RouteName] nvarchar(128) NULL,
        [Description] nvarchar(512) NULL,
        [Scheme] nvarchar(16) NOT NULL DEFAULT 'https',
        [AddressHost] nvarchar(255) NOT NULL,
        [AddressPort] int NOT NULL DEFAULT 443,
        [AddressBasePath] nvarchar(255) NULL,
        [AddressPath] nvarchar(255) NULL,
        [AddressQueryString] nvarchar(500) NULL,
        [Headers] nvarchar(max) NULL,
        [TimeoutSeconds] int NOT NULL,
        [HttpMethods] nvarchar(64) NOT NULL DEFAULT 'ALL',
        [AllowAnonymous] bit NOT NULL DEFAULT 0,
        [RequiredScope] bit NOT NULL DEFAULT 0,
        [ApiScopeId] int NULL,
        [ScopeName] nvarchar(200) NULL,
        [AuthenticationSchemes] nvarchar(255) NULL DEFAULT 'Bearer',
        [IsEnabled] bit NOT NULL DEFAULT 1,
        [Priority] int NOT NULL DEFAULT 0,
        [EnableCaching] bit NOT NULL DEFAULT 0,
        [ForwardOriginalHost] bit NOT NULL DEFAULT 1,
        [CreatedAt] datetime2 NOT NULL,
        [UpdatedAt] datetime2 NULL
    );
    CREATE INDEX [IX_GatewayRoutes_MatchPattern] ON [GatewayRoutes] ([MatchPattern]);
    CREATE INDEX [IX_GatewayRoutes_Priority] ON [GatewayRoutes] ([Priority]);
    CREATE INDEX [IX_GatewayRoutes_IsEnabled] ON [GatewayRoutes] ([IsEnabled]);
END
";
                    await appDb.Database.ExecuteSqlRawAsync(sql);
                }
            }
            catch
            {
                // Ignorujemy błędy awaryjnego tworzenia
            }
        }
    }

    public static async Task EnsureSeedDataAsync(WebApplication app)
    {
        using var scope = app.Services.GetRequiredService<IServiceScopeFactory>().CreateScope();

        // 1. Zapewnienie struktury bazy danych dla wszystkich DbContextów
        var appDb = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
        await EnsureTablesCreatedAsync(appDb);

        var configDb = scope.ServiceProvider.GetRequiredService<ConfigurationDbContext>();
        await EnsureTablesCreatedAsync(configDb);

        var persistedGrantDb = scope.ServiceProvider.GetRequiredService<PersistedGrantDbContext>();
        await EnsureTablesCreatedAsync(persistedGrantDb);

        // 2. Utworzenie ról Identity
        var roleManager = scope.ServiceProvider.GetRequiredService<RoleManager<IdentityRole>>();
        var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();

        string[] roles = ["Admin", "User", "Manager"];
        foreach (var role in roles)
        {
            if (!await roleManager.RoleExistsAsync(role))
            {
                await roleManager.CreateAsync(new IdentityRole(role));
            }
        }

        // 3. Utworzenie domyślnego konta Administratora
        var adminUser = await userManager.FindByNameAsync("admin");
        if (adminUser == null)
        {
            adminUser = new ApplicationUser
            {
                UserName = "admin",
                Email = "admin@identityserver.local",
                EmailConfirmed = true,
                FullName = "Administrator Systemu"
            };

            var result = await userManager.CreateAsync(adminUser, "Pass123$");
            if (result.Succeeded)
            {
                await userManager.AddToRoleAsync(adminUser, "Admin");
            }
        }

        // 4. Utworzenie konta standardowego użytkownika testowego
        var testUser = await userManager.FindByNameAsync("jan.kowalski");
        if (testUser == null)
        {
            testUser = new ApplicationUser
            {
                UserName = "jan.kowalski",
                Email = "jan.kowalski@example.com",
                EmailConfirmed = true,
                FullName = "Jan Kowalski"
            };

            var result = await userManager.CreateAsync(testUser, "Pass123$");
            if (result.Succeeded)
            {
                await userManager.AddToRoleAsync(testUser, "User");
            }
        }

        // 5. Seedowanie Zasobów Tożsamości (IdentityResources)
        if (!await configDb.IdentityResources.AnyAsync())
        {
            configDb.IdentityResources.AddRange(
                new IdentityResources.OpenId().ToEntity(),
                new IdentityResources.Profile().ToEntity(),
                new IdentityResources.Email().ToEntity()
            );
            await configDb.SaveChangesAsync();
        }

        // 6. Seedowanie Zakresów API (ApiScopes)
        if (!await configDb.ApiScopes.AnyAsync())
        {
            configDb.ApiScopes.AddRange(
                new ApiScope("api1", "Dostęp do API Produkty i Zamówienia").ToEntity(),
                new ApiScope("api.read", "Tylko odczyt danych API").ToEntity(),
                new ApiScope("api.write", "Zapis i modyfikacja danych API").ToEntity()
            );
            await configDb.SaveChangesAsync();
        }

        // 7. Seedowanie Przykładowych Klientów OIDC / OAuth2
        if (!await configDb.Clients.AnyAsync())
        {
            configDb.Clients.AddRange(
                // Klient Maszyna-Maszyna (Client Credentials Flow)
                new Client
                {
                    ClientId = "m2m.client",
                    ClientName = "Usługa w tle (Machine-to-Machine)",
                    AllowedGrantTypes = GrantTypes.ClientCredentials,
                    ClientSecrets = { new Secret("secret".Sha256()) },
                    AllowedScopes = { "api1", "api.read", "api.write" }
                }.ToEntity(),

                // Klient Interaktywny (Authorization Code Flow + PKCE)
                new Client
                {
                    ClientId = "interactive.mvc",
                    ClientName = "Aplikacja Webowa ASP.NET Core MVC / SPA",
                    AllowedGrantTypes = GrantTypes.Code,
                    RequirePkce = true,
                    RequireClientSecret = false,
                    RedirectUris = { "https://localhost:5002/signin-oidc" },
                    PostLogoutRedirectUris = { "https://localhost:5002/signout-callback-oidc" },
                    AllowedScopes = { "openid", "profile", "email", "api1" },
                    AllowOfflineAccess = true // Obsługa Refresh Tokens
                }.ToEntity()
            );
            await configDb.SaveChangesAsync();
        }

        // 8. Seedowanie Dynamicznych Dostawców Tożsamości OIDC (Dynamic External Providers)
        if (!await appDb.FederationProviders.AnyAsync())
        {
            appDb.FederationProviders.AddRange(
                // 1. Microsoft Entra ID (Azure Active Directory)
                new OidcFederationProvider
                {
                    Id = Guid.NewGuid().ToString(),
                    Scheme = "entra-id",
                    DisplayName = "Microsoft Entra ID",
                    Authority = "https://login.microsoftonline.com/organizations/v2.0",
                    ClientId = "00000000-0000-0000-0000-000000000001",
                    ClientSecret = "entra-sample-client-secret",
                    ResponseType = "code",
                    Scope = "openid profile email",
                    CallbackPath = "/signin-oidc-entra",
                    SignedOutCallbackPath = "/signout-callback-oidc",
                    UsePkce = true,
                    GetClaimsFromUserInfoEndpoint = true,
                    SaveTokens = true,
                    IsEnabled = true,
                    AutoProvisionUsers = true,
                    DefaultRole = "User",
                    IconType = "microsoft",
                    ButtonColor = "#0078D4",
                    Prompt = "select_account"
                },

                // 2. Azure AD B2C (Customer Identity and Access Management)
                new OidcFederationProvider
                {
                    Id = Guid.NewGuid().ToString(),
                    Scheme = "azure-b2c",
                    DisplayName = "Azure AD B2C (CIAM)",
                    Authority = "https://mytenant.b2clogin.com/mytenant.onmicrosoft.com/b2c_1_susi/v2.0/",
                    ClientId = "00000000-0000-0000-0000-000000000002",
                    ClientSecret = "b2c-sample-client-secret",
                    ResponseType = "code",
                    Scope = "openid profile email",
                    CallbackPath = "/signin-oidc-b2c",
                    SignedOutCallbackPath = "/signout-callback-oidc",
                    UsePkce = true,
                    GetClaimsFromUserInfoEndpoint = true,
                    SaveTokens = true,
                    IsEnabled = true,
                    AutoProvisionUsers = true,
                    DefaultRole = "User",
                    IconType = "azure",
                    ButtonColor = "#0089D6",
                    AdditionalParametersJson = "{\"p\": \"b2c_1_susi\"}"
                },

                // 3. Google Workspace / Google Accounts OIDC
                new OidcFederationProvider
                {
                    Id = Guid.NewGuid().ToString(),
                    Scheme = "google-oidc",
                    DisplayName = "Google Workspace",
                    Authority = "https://accounts.google.com",
                    ClientId = "000000000000-samplegoogleclientid.apps.googleusercontent.com",
                    ClientSecret = "GOCSPX-SampleGoogleClientSecret",
                    ResponseType = "code",
                    Scope = "openid profile email",
                    CallbackPath = "/signin-oidc-google",
                    SignedOutCallbackPath = "/signout-callback-oidc",
                    UsePkce = true,
                    GetClaimsFromUserInfoEndpoint = true,
                    SaveTokens = true,
                    IsEnabled = true,
                    AutoProvisionUsers = true,
                    DefaultRole = "User",
                    IconType = "google",
                    ButtonColor = "#4285F4",
                    Prompt = "select_account"
                }
            );
            await appDb.SaveChangesAsync();
        }

        // 9. Seedowanie Tras API Gateway (Reguły Reverse Proxy)
        if (!await appDb.GatewayRoutes.AnyAsync())
        {
            var api1Scope = await configDb.ApiScopes.FirstOrDefaultAsync(s => s.Name == "api1");
            var apiReadScope = await configDb.ApiScopes.FirstOrDefaultAsync(s => s.Name == "api.read");

            appDb.GatewayRoutes.AddRange(
                // 1. Serwis Użytkowników i Kont (Wymaga JWT Bearer + Scope api1)
                new GatewayRoute
                {
                    MatchPattern = @"^/api/v1/users(/.*)?$",
                    RouteName = "Serwis Użytkowników (Users Service)",
                    Description = "Routing do wewnętrznego mikroserwisu użytkowników z wymaganym tokenem JWT i uprawnieniem api1.",
                    Scheme = "https",
                    AddressHost = "users-service.internal",
                    AddressPort = 8443,
                    AddressBasePath = "/v1/users",
                    AddressPath = null,
                    AddressQueryString = null,
                    Headers = "{\"X-Forwarded-Gateway\": \"Quorum.Gateway\", \"X-Service-Name\": \"UsersAPI\"}",
                    TimeoutSeconds = 30,
                    HttpMethods = "GET,POST,PUT,DELETE",
                    AllowAnonymous = false,
                    RequiredScope = true,
                    ApiScopeId = api1Scope?.Id,
                    ScopeName = "api1",
                    AuthenticationSchemes = "Bearer",
                    IsEnabled = true,
                    Priority = 100,
                    EnableCaching = false,
                    ForwardOriginalHost = true,
                    CreatedAt = DateTime.UtcNow
                },

                // 2. Publiczny Katalog Produktów (Anonimowy dostęp, Classic Proxy)
                new GatewayRoute
                {
                    MatchPattern = @"^/api/v1/catalog(/.*)?$",
                    RouteName = "Katalog Produktów (Catalog Service)",
                    Description = "Publiczny routing do katalogu produktów bez konieczności przekazywania tokenu JWT (AllowAnonymous).",
                    Scheme = "http",
                    AddressHost = "catalog-api.local",
                    AddressPort = 8080,
                    AddressBasePath = "/public/catalog",
                    AddressPath = null,
                    AddressQueryString = "channel=web&region=eu",
                    Headers = "{\"X-Cache-Policy\": \"public-max-age-300\"}",
                    TimeoutSeconds = 15,
                    HttpMethods = "GET",
                    AllowAnonymous = true,
                    RequiredScope = false,
                    ApiScopeId = null,
                    ScopeName = null,
                    AuthenticationSchemes = null,
                    IsEnabled = true,
                    Priority = 80,
                    EnableCaching = true,
                    ForwardOriginalHost = false,
                    CreatedAt = DateTime.UtcNow
                },

                // 3. Mikroserwis Zamówień i Płatności (Wymaga JWT Bearer + Scope api.read)
                new GatewayRoute
                {
                    MatchPattern = @"^/api/v1/orders(/.*)?$",
                    RouteName = "Serwis Zamówień (Orders Service)",
                    Description = "Bezpieczne proxy dla transakcji zakupowych i statusów zamówień.",
                    Scheme = "https",
                    AddressHost = "orders.internal.mesh",
                    AddressPort = 9443,
                    AddressBasePath = "/api/orders",
                    AddressPath = null,
                    AddressQueryString = null,
                    Headers = "{\"X-Gateway-Env\": \"Production\"}",
                    TimeoutSeconds = 45,
                    HttpMethods = "GET,POST,PUT",
                    AllowAnonymous = false,
                    RequiredScope = true,
                    ApiScopeId = apiReadScope?.Id,
                    ScopeName = "api.read",
                    AuthenticationSchemes = "Bearer",
                    IsEnabled = true,
                    Priority = 90,
                    EnableCaching = false,
                    ForwardOriginalHost = true,
                    CreatedAt = DateTime.UtcNow
                }
            );
            await appDb.SaveChangesAsync();
        }
    }
}
