<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10"/>
        <PackageReference Include="Open.IdentityServer.EntityFramework.Storage" Version="2.0.0" />
        <PackageReference Include="Open.IdentityServer.EntityFramework" Version="2.0.0" />

        <!-- Open.IdentityServer Entity Framework -->


        <!-- ASP.NET Core Identity & EF Core -->
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.10" />

        <!-- Bazy Danych (SQLite domyślnie + PostgreSQL + Microsoft SQL Server) -->
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    </ItemGroup>
</Project>
