import { TableModel } from '../types/migrations';

export const EF_CORE_TABLES: TableModel[] = [
  // --- 1. Bramka Gateway & Federacje ---
  {
    name: 'GatewayRoutes',
    category: 'gateway',
    categoryLabel: 'API Gateway & Trasy',
    description: 'Konfiguracja tras i reguł proxy API Gateway z obsługą regex, transformacji i autoryzacji',
    columns: [
      { name: 'Id', type: 'integer', typeByEngine: { sqlserver: 'int IDENTITY(1,1)', postgres: 'serial', sqlite: 'INTEGER PRIMARY KEY AUTOINCREMENT', oracle: 'NUMBER GENERATED BY DEFAULT AS IDENTITY' }, nullable: false, isPrimaryKey: true, isAutoIncrement: true },
      { name: 'MatchPattern', type: 'varchar(255)', typeByEngine: { sqlserver: 'nvarchar(255)', postgres: 'varchar(255)', sqlite: 'TEXT', oracle: 'VARCHAR2(255)' }, nullable: false },
      { name: 'RouteName', type: 'varchar(128)', typeByEngine: { sqlserver: 'nvarchar(128)', postgres: 'varchar(128)', sqlite: 'TEXT', oracle: 'VARCHAR2(128)' }, nullable: true },
      { name: 'Description', type: 'varchar(512)', typeByEngine: { sqlserver: 'nvarchar(512)', postgres: 'varchar(512)', sqlite: 'TEXT', oracle: 'VARCHAR2(512)' }, nullable: true },
      { name: 'Scheme', type: 'varchar(16)', typeByEngine: { sqlserver: 'nvarchar(16)', postgres: 'varchar(16)', sqlite: 'TEXT', oracle: 'VARCHAR2(16)' }, nullable: false, defaultValue: "'https'" },
      { name: 'AddressHost', type: 'varchar(255)', typeByEngine: { sqlserver: 'nvarchar(255)', postgres: 'varchar(255)', sqlite: 'TEXT', oracle: 'VARCHAR2(255)' }, nullable: false },
      { name: 'AddressPort', type: 'integer', typeByEngine: { sqlserver: 'int', postgres: 'integer', sqlite: 'INTEGER', oracle: 'NUMBER(5)' }, nullable: false, defaultValue: '443' },
      { name: 'AddressBasePath', type: 'varchar(255)', typeByEngine: { sqlserver: 'nvarchar(255)', postgres: 'varchar(255)', sqlite: 'TEXT', oracle: 'VARCHAR2(255)' }, nullable: true },
      { name: 'AddressPath', type: 'varchar(255)', typeByEngine: { sqlserver: 'nvarchar(255)', postgres: 'varchar(255)', sqlite: 'TEXT', oracle: 'VARCHAR2(255)' }, nullable: true },
      { name: 'AddressQueryString', type: 'varchar(500)', typeByEngine: { sqlserver: 'nvarchar(500)', postgres: 'varchar(500)', sqlite: 'TEXT', oracle: 'VARCHAR2(500)' }, nullable: true },
      { name: 'HttpMethods', type: 'varchar(64)', typeByEngine: { sqlserver: 'nvarchar(64)', postgres: 'varchar(64)', sqlite: 'TEXT', oracle: 'VARCHAR2(64)' }, nullable: false, defaultValue: "'ALL'" },
      { name: 'AuthenticationSchemes', type: 'varchar(255)', typeByEngine: { sqlserver: 'nvarchar(255)', postgres: 'varchar(255)', sqlite: 'TEXT', oracle: 'VARCHAR2(255)' }, nullable: true, defaultValue: "'Bearer'" },
      { name: 'IsEnabled', type: 'boolean', typeByEngine: { sqlserver: 'bit', postgres: 'boolean', sqlite: 'INTEGER', oracle: 'NUMBER(1)' }, nullable: false, defaultValue: '1' },
      { name: 'Priority', type: 'integer', typeByEngine: { sqlserver: 'int', postgres: 'integer', sqlite: 'INTEGER', oracle: 'NUMBER(10)' }, nullable: false, defaultValue: '0' },
      { name: 'AllowAnonymous', type: 'boolean', typeByEngine: { sqlserver: 'bit', postgres: 'boolean', sqlite: 'INTEGER', oracle: 'NUMBER(1)' }, nullable: false, defaultValue: '0' },
      { name: 'RequiredScope', type: 'boolean', typeByEngine: { sqlserver: 'bit', postgres: 'boolean', sqlite: 'INTEGER', oracle: 'NUMBER(1)' }, nullable: false, defaultValue: '0' },
      { name: 'ScopeName', type: 'varchar(500)', typeByEngine: { sqlserver: 'nvarchar(500)', postgres: 'varchar(500)', sqlite: 'TEXT', oracle: 'VARCHAR2(500)' }, nullable: true },
      { name: 'RateLimitPerMinute', type: 'integer', typeByEngine: { sqlserver: 'int', postgres: 'integer', sqlite: 'INTEGER', oracle: 'NUMBER(10)' }, nullable: true },
      { name: 'TimeoutSeconds', type: 'integer', typeByEngine: { sqlserver: 'int', postgres: 'integer', sqlite: 'INTEGER', oracle: 'NUMBER(10)' }, nullable: false, defaultValue: '30' },
      { name: 'TransformBody', type: 'boolean', typeByEngine: { sqlserver: 'bit', postgres: 'boolean', sqlite: 'INTEGER', oracle: 'NUMBER(1)' }, nullable: false, defaultValue: '0' },
      { name: 'CreatedAt', type: 'timestamp', typeByEngine: { sqlserver: 'datetime2', postgres: 'timestamp with time zone', sqlite: 'TEXT', oracle: 'TIMESTAMP WITH TIME ZONE' }, nullable: false },
      { name: 'UpdatedAt', type: 'timestamp', typeByEngine: { sqlserver: 'datetime2', postgres: 'timestamp with time zone', sqlite: 'TEXT', oracle: 'TIMESTAMP WITH TIME ZONE' }, nullable: true }
    ],
    indexes: [
      { name: 'IX_GatewayRoutes_MatchPattern', tableName: 'GatewayRoutes', columns: ['MatchPattern'] },
      { name: 'IX_GatewayRoutes_Priority', tableName: 'GatewayRoutes', columns: ['Priority'] },
      { name: 'IX_GatewayRoutes_IsEnabled', tableName: 'GatewayRoutes', columns: ['IsEnabled'] }
    ],
    foreignKeys: []
  },
  {
    name: 'GatewayRouteScopes',
    category: 'gateway',
    categoryLabel: 'API Gateway & Trasy',
    description: 'Mapowanie wymaganych zakresów (Scopes) przypisanych do tras routingu',
    columns: [
      { name: 'Id', type: 'integer', typeByEngine: { sqlserver: 'int IDENTITY(1,1)', postgres: 'serial', sqlite: 'INTEGER PRIMARY KEY AUTOINCREMENT', oracle: 'NUMBER GENERATED BY DEFAULT AS IDENTITY' }, nullable: false, isPrimaryKey: true, isAutoIncrement: true },
      { name: 'GatewayRouteId', type: 'integer', typeByEngine: { sqlserver: 'int', postgres: 'integer', sqlite: 'INTEGER', oracle: 'NUMBER(10)' }, nullable: false },
      { name: 'Scope', type: 'varchar(200)', typeByEngine: { sqlserver: 'nvarchar(200)', postgres: 'varchar(200)', sqlite: 'TEXT', oracle: 'VARCHAR2(200)' }, nullable: false }
    ],
    indexes: [
      { name: 'IX_GatewayRouteScopes_Route_Scope', tableName: 'GatewayRouteScopes', columns: ['GatewayRouteId', 'Scope'] }
    ],
    foreignKeys: [
      { name: 'FK_GatewayRouteScopes_GatewayRoutes_GatewayRouteId', tableName: 'GatewayRouteScopes', column: 'GatewayRouteId', principalTable: 'GatewayRoutes', principalColumn: 'Id', onDelete: 'CASCADE' }
    ]
  },
  {
    name: 'FederationProviders',
    category: 'gateway',
    categoryLabel: 'API Gateway & Trasy',
    description: 'Dynamiczni zewnętrzni dostawcy tożsamości OIDC (Google Workspace, Entra ID, Keycloak)',
    columns: [
      { name: 'Id', type: 'varchar(128)', typeByEngine: { sqlserver: 'nvarchar(128)', postgres: 'varchar(128)', sqlite: 'TEXT PRIMARY KEY', oracle: 'VARCHAR2(128) PRIMARY KEY' }, nullable: false, isPrimaryKey: true },
      { name: 'Scheme', type: 'varchar(64)', typeByEngine: { sqlserver: 'nvarchar(64)', postgres: 'varchar(64)', sqlite: 'TEXT', oracle: 'VARCHAR2(64)' }, nullable: false },
      { name: 'DisplayName', type: 'varchar(128)', typeByEngine: { sqlserver: 'nvarchar(128)', postgres: 'varchar(128)', sqlite: 'TEXT', oracle: 'VARCHAR2(128)' }, nullable: false },
      { name: 'Authority', type: 'varchar(512)', typeByEngine: { sqlserver: 'nvarchar(512)', postgres: 'varchar(512)', sqlite: 'TEXT', oracle: 'VARCHAR2(512)' }, nullable: false },
      { name: 'ClientId', type: 'varchar(256)', typeByEngine: { sqlserver: 'nvarchar(256)', postgres: 'varchar(256)', sqlite: 'TEXT', oracle: 'VARCHAR2(256)' }, nullable: false },
      { name: 'ClientSecret', type: 'varchar(512)', typeByEngine: { sqlserver: 'nvarchar(512)', postgres: 'varchar(512)', sqlite: 'TEXT', oracle: 'VARCHAR2(512)' }, nullable: true },
      { name: 'ResponseType', type: 'varchar(32)', typeByEngine: { sqlserver: 'nvarchar(32)', postgres: 'varchar(32)', sqlite: 'TEXT', oracle: 'VARCHAR2(32)' }, nullable: false, defaultValue: "'code'" },
      { name: 'Scope', type: 'varchar(512)', typeByEngine: { sqlserver: 'nvarchar(512)', postgres: 'varchar(512)', sqlite: 'TEXT', oracle: 'VARCHAR2(512)' }, nullable: false, defaultValue: "'openid profile email'" },
      { name: 'CallbackPath', type: 'varchar(256)', typeByEngine: { sqlserver: 'nvarchar(256)', postgres: 'varchar(256)', sqlite: 'TEXT', oracle: 'VARCHAR2(256)' }, nullable: false },
      { name: 'SignedOutCallbackPath', type: 'varchar(256)', typeByEngine: { sqlserver: 'nvarchar(256)', postgres: 'varchar(256)', sqlite: 'TEXT', oracle: 'VARCHAR2(256)' }, nullable: true },
      { name: 'UsePkce', type: 'boolean', typeByEngine: { sqlserver: 'bit', postgres: 'boolean', sqlite: 'INTEGER', oracle: 'NUMBER(1)' }, nullable: false, defaultValue: '1' },
      { name: 'GetClaimsFromUserInfoEndpoint', type: 'boolean', typeByEngine: { sqlserver: 'bit', postgres: 'boolean', sqlite: 'INTEGER', oracle: 'NUMBER(1)' }, nullable: false, defaultValue: '1' },
      { name: 'SaveTokens', type: 'boolean', typeByEngine: { sqlserver: 'bit', postgres: 'boolean', sqlite: 'INTEGER', oracle: 'NUMBER(1)' }, nullable: false, defaultValue: '1' },
      { name: 'IsEnabled', type: 'boolean', typeByEngine: { sqlserver: 'bit', postgres: 'boolean', sqlite: 'INTEGER', oracle: 'NUMBER(1)' }, nullable: false, defaultValue: '1' },
      { name: 'DefaultRole', type: 'varchar(64)', typeByEngine: { sqlserver: 'nvarchar(64)', postgres: 'varchar(64)', sqlite: 'TEXT', oracle: 'VARCHAR2(64)' }, nullable: true },
      { name: 'IconType', type: 'varchar(32)', typeByEngine: { sqlserver: 'nvarchar(32)', postgres: 'varchar(32)', sqlite: 'TEXT', oracle: 'VARCHAR2(32)' }, nullable: true },
      { name: 'CreatedAt', type: 'timestamp', typeByEngine: { sqlserver: 'datetime2', postgres: 'timestamp with time zone', sqlite: 'TEXT', oracle: 'TIMESTAMP WITH TIME ZONE' }, nullable: false },
      { name: 'UpdatedAt', type: 'timestamp', typeByEngine: { sqlserver: 'datetime2', postgres: 'timestamp with time zone', sqlite: 'TEXT', oracle: 'TIMESTAMP WITH TIME ZONE' }, nullable: true }
    ],
    indexes: [
      { name: 'IX_FederationProviders_Scheme', tableName: 'FederationProviders', columns: ['Scheme'], isUnique: true }
    ],
    foreignKeys: []
  },

  // --- 2. ASP.NET Core Identity ---
  {
    name: 'AspNetUsers',
    category: 'identity',
    categoryLabel: 'ASP.NET Core Identity',
    description: 'Główna tabela kont użytkowników z rozszerzonym profilem Quorum',
    columns: [
      { name: 'Id', type: 'varchar(450)', typeByEngine: { sqlserver: 'nvarchar(450)', postgres: 'varchar(450)', sqlite: 'TEXT PRIMARY KEY', oracle: 'VARCHAR2(450) PRIMARY KEY' }, nullable: false, isPrimaryKey: true },
      { name: 'UserName', type: 'varchar(256)', typeByEngine: { sqlserver: 'nvarchar(256)', postgres: 'varchar(256)', sqlite: 'TEXT', oracle: 'VARCHAR2(256)' }, nullable: true },
      { name: 'NormalizedUserName', type: 'varchar(256)', typeByEngine: { sqlserver: 'nvarchar(256)', postgres: 'varchar(256)', sqlite: 'TEXT', oracle: 'VARCHAR2(256)' }, nullable: true },
      { name: 'Email', type: 'varchar(256)', typeByEngine: { sqlserver: 'nvarchar(256)', postgres: 'varchar(256)', sqlite: 'TEXT', oracle: 'VARCHAR2(256)' }, nullable: true },
      { name: 'NormalizedEmail', type: 'varchar(256)', typeByEngine: { sqlserver: 'nvarchar(256)', postgres: 'varchar(256)', sqlite: 'TEXT', oracle: 'VARCHAR2(256)' }, nullable: true },
      { name: 'EmailConfirmed', type: 'boolean', typeByEngine: { sqlserver: 'bit', postgres: 'boolean', sqlite: 'INTEGER', oracle: 'NUMBER(1)' }, nullable: false, defaultValue: '0' },
      { name: 'PasswordHash', type: 'varchar(max)', typeByEngine: { sqlserver: 'nvarchar(max)', postgres: 'text', sqlite: 'TEXT', oracle: 'CLOB' }, nullable: true },
      { name: 'SecurityStamp', type: 'varchar(max)', typeByEngine: { sqlserver: 'nvarchar(max)', postgres: 'text', sqlite: 'TEXT', oracle: 'CLOB' }, nullable: true },
      { name: 'ConcurrencyStamp', type: 'varchar(max)', typeByEngine: { sqlserver: 'nvarchar(max)', postgres: 'text', sqlite: 'TEXT', oracle: 'CLOB' }, nullable: true },
      { name: 'PhoneNumber', type: 'varchar(max)', typeByEngine: { sqlserver: 'nvarchar(max)', postgres: 'text', sqlite: 'TEXT', oracle: 'VARCHAR2(100)' }, nullable: true },
      { name: 'PhoneNumberConfirmed', type: 'boolean', typeByEngine: { sqlserver: 'bit', postgres: 'boolean', sqlite: 'INTEGER', oracle: 'NUMBER(1)' }, nullable: false, defaultValue: '0' },
      { name: 'TwoFactorEnabled', type: 'boolean', typeByEngine: { sqlserver: 'bit', postgres: 'boolean', sqlite: 'INTEGER', oracle: 'NUMBER(1)' }, nullable: false, defaultValue: '0' },
      { name: 'LockoutEnd', type: 'timestamp', typeByEngine: { sqlserver: 'datetimeoffset', postgres: 'timestamp with time zone', sqlite: 'TEXT', oracle: 'TIMESTAMP WITH TIME ZONE' }, nullable: true },
      { name: 'LockoutEnabled', type: 'boolean', typeByEngine: { sqlserver: 'bit', postgres: 'boolean', sqlite: 'INTEGER', oracle: 'NUMBER(1)' }, nullable: false, defaultValue: '0' },
      { name: 'AccessFailedCount', type: 'integer', typeByEngine: { sqlserver: 'int', postgres: 'integer', sqlite: 'INTEGER', oracle: 'NUMBER(10)' }, nullable: false, defaultValue: '0' },
      { name: 'FullName', type: 'varchar(256)', typeByEngine: { sqlserver: 'nvarchar(256)', postgres: 'varchar(256)', sqlite: 'TEXT', oracle: 'VARCHAR2(256)' }, nullable: true },
      { name: 'CreatedAt', type: 'timestamp', typeByEngine: { sqlserver: 'datetime2', postgres: 'timestamp with time zone', sqlite: 'TEXT', oracle: 'TIMESTAMP WITH TIME ZONE' }, nullable: false }
    ],
    indexes: [
      { name: 'EmailIndex', tableName: 'AspNetUsers', columns: ['NormalizedEmail'] },
      { name: 'UserNameIndex', tableName: 'AspNetUsers', columns: ['NormalizedUserName'], isUnique: true }
    ],
    foreignKeys: []
  },
  {
    name: 'AspNetRoles',
    category: 'identity',
    categoryLabel: 'ASP.NET Core Identity',
    description: 'Tabela ról systemowych (Admin, Manager, User, Operator)',
    columns: [
      { name: 'Id', type: 'varchar(450)', typeByEngine: { sqlserver: 'nvarchar(450)', postgres: 'varchar(450)', sqlite: 'TEXT PRIMARY KEY', oracle: 'VARCHAR2(450) PRIMARY KEY' }, nullable: false, isPrimaryKey: true },
      { name: 'Name', type: 'varchar(256)', typeByEngine: { sqlserver: 'nvarchar(256)', postgres: 'varchar(256)', sqlite: 'TEXT', oracle: 'VARCHAR2(256)' }, nullable: true },
      { name: 'NormalizedName', type: 'varchar(256)', typeByEngine: { sqlserver: 'nvarchar(256)', postgres: 'varchar(256)', sqlite: 'TEXT', oracle: 'VARCHAR2(256)' }, nullable: true },
      { name: 'ConcurrencyStamp', type: 'varchar(max)', typeByEngine: { sqlserver: 'nvarchar(max)', postgres: 'text', sqlite: 'TEXT', oracle: 'CLOB' }, nullable: true }
    ],
    indexes: [
      { name: 'RoleNameIndex', tableName: 'AspNetRoles', columns: ['NormalizedName'], isUnique: true }
    ],
    foreignKeys: []
  },
  {
    name: 'AspNetUserRoles',
    category: 'identity',
    categoryLabel: 'ASP.NET Core Identity',
    description: 'Przypisania ról do użytkowników',
    columns: [
      { name: 'UserId', type: 'varchar(450)', typeByEngine: { sqlserver: 'nvarchar(450)', postgres: 'varchar(450)', sqlite: 'TEXT', oracle: 'VARCHAR2(450)' }, nullable: false, isPrimaryKey: true },
      { name: 'RoleId', type: 'varchar(450)', typeByEngine: { sqlserver: 'nvarchar(450)', postgres: 'varchar(450)', sqlite: 'TEXT', oracle: 'VARCHAR2(450)' }, nullable: false, isPrimaryKey: true }
    ],
    indexes: [
      { name: 'IX_AspNetUserRoles_RoleId', tableName: 'AspNetUserRoles', columns: ['RoleId'] }
    ],
    foreignKeys: [
      { name: 'FK_AspNetUserRoles_AspNetUsers_UserId', tableName: 'AspNetUserRoles', column: 'UserId', principalTable: 'AspNetUsers', principalColumn: 'Id', onDelete: 'CASCADE' },
      { name: 'FK_AspNetUserRoles_AspNetRoles_RoleId', tableName: 'AspNetUserRoles', column: 'RoleId', principalTable: 'AspNetRoles', principalColumn: 'Id', onDelete: 'CASCADE' }
    ]
  },
  {
    name: 'AspNetUserClaims',
    category: 'identity',
    categoryLabel: 'ASP.NET Core Identity',
    description: 'Dodatkowe roszczenia (Claims) przypisane do użytkowników',
    columns: [
      { name: 'Id', type: 'integer', typeByEngine: { sqlserver: 'int IDENTITY(1,1)', postgres: 'serial', sqlite: 'INTEGER PRIMARY KEY AUTOINCREMENT', oracle: 'NUMBER GENERATED BY DEFAULT AS IDENTITY' }, nullable: false, isPrimaryKey: true, isAutoIncrement: true },
      { name: 'UserId', type: 'varchar(450)', typeByEngine: { sqlserver: 'nvarchar(450)', postgres: 'varchar(450)', sqlite: 'TEXT', oracle: 'VARCHAR2(450)' }, nullable: false },
      { name: 'ClaimType', type: 'varchar(max)', typeByEngine: { sqlserver: 'nvarchar(max)', postgres: 'text', sqlite: 'TEXT', oracle: 'VARCHAR2(256)' }, nullable: true },
      { name: 'ClaimValue', type: 'varchar(max)', typeByEngine: { sqlserver: 'nvarchar(max)', postgres: 'text', sqlite: 'TEXT', oracle: 'VARCHAR2(1024)' }, nullable: true }
    ],
    indexes: [
      { name: 'IX_AspNetUserClaims_UserId', tableName: 'AspNetUserClaims', columns: ['UserId'] }
    ],
    foreignKeys: [
      { name: 'FK_AspNetUserClaims_AspNetUsers_UserId', tableName: 'AspNetUserClaims', column: 'UserId', principalTable: 'AspNetUsers', principalColumn: 'Id', onDelete: 'CASCADE' }
    ]
  },

  // --- 3. Open.IdentityServer (Konfiguracja Klientów & Zakresów) ---
  {
    name: 'Clients',
    category: 'openiddict',
    categoryLabel: 'Klienci i Zakresy OIDC',
    description: 'Klienci protokołów OAuth 2.0 / OIDC z parametrami bezpieczeństwa, PKCE i tokenów',
    columns: [
      { name: 'Id', type: 'integer', typeByEngine: { sqlserver: 'int IDENTITY(1,1)', postgres: 'serial', sqlite: 'INTEGER PRIMARY KEY AUTOINCREMENT', oracle: 'NUMBER GENERATED BY DEFAULT AS IDENTITY' }, nullable: false, isPrimaryKey: true, isAutoIncrement: true },
      { name: 'ClientId', type: 'varchar(200)', typeByEngine: { sqlserver: 'nvarchar(200)', postgres: 'varchar(200)', sqlite: 'TEXT', oracle: 'VARCHAR2(200)' }, nullable: false },
      { name: 'ClientName', type: 'varchar(200)', typeByEngine: { sqlserver: 'nvarchar(200)', postgres: 'varchar(200)', sqlite: 'TEXT', oracle: 'VARCHAR2(200)' }, nullable: true },
      { name: 'Description', type: 'varchar(1000)', typeByEngine: { sqlserver: 'nvarchar(1000)', postgres: 'varchar(1000)', sqlite: 'TEXT', oracle: 'VARCHAR2(1000)' }, nullable: true },
      { name: 'ClientUri', type: 'varchar(2000)', typeByEngine: { sqlserver: 'nvarchar(2000)', postgres: 'varchar(2000)', sqlite: 'TEXT', oracle: 'VARCHAR2(2000)' }, nullable: true },
      { name: 'Enabled', type: 'boolean', typeByEngine: { sqlserver: 'bit', postgres: 'boolean', sqlite: 'INTEGER', oracle: 'NUMBER(1)' }, nullable: false, defaultValue: '1' },
      { name: 'ProtocolType', type: 'varchar(200)', typeByEngine: { sqlserver: 'nvarchar(200)', postgres: 'varchar(200)', sqlite: 'TEXT', oracle: 'VARCHAR2(200)' }, nullable: false, defaultValue: "'oidc'" },
      { name: 'RequireClientSecret', type: 'boolean', typeByEngine: { sqlserver: 'bit', postgres: 'boolean', sqlite: 'INTEGER', oracle: 'NUMBER(1)' }, nullable: false, defaultValue: '1' },
      { name: 'RequireConsent', type: 'boolean', typeByEngine: { sqlserver: 'bit', postgres: 'boolean', sqlite: 'INTEGER', oracle: 'NUMBER(1)' }, nullable: false, defaultValue: '0' },
      { name: 'RequirePkce', type: 'boolean', typeByEngine: { sqlserver: 'bit', postgres: 'boolean', sqlite: 'INTEGER', oracle: 'NUMBER(1)' }, nullable: false, defaultValue: '1' },
      { name: 'AllowPlainTextPkce', type: 'boolean', typeByEngine: { sqlserver: 'bit', postgres: 'boolean', sqlite: 'INTEGER', oracle: 'NUMBER(1)' }, nullable: false, defaultValue: '0' },
      { name: 'AllowAccessTokensViaBrowser', type: 'boolean', typeByEngine: { sqlserver: 'bit', postgres: 'boolean', sqlite: 'INTEGER', oracle: 'NUMBER(1)' }, nullable: false, defaultValue: '0' },
      { name: 'AllowOfflineAccess', type: 'boolean', typeByEngine: { sqlserver: 'bit', postgres: 'boolean', sqlite: 'INTEGER', oracle: 'NUMBER(1)' }, nullable: false, defaultValue: '0' },
      { name: 'IdentityTokenLifetime', type: 'integer', typeByEngine: { sqlserver: 'int', postgres: 'integer', sqlite: 'INTEGER', oracle: 'NUMBER(10)' }, nullable: false, defaultValue: '300' },
      { name: 'AccessTokenLifetime', type: 'integer', typeByEngine: { sqlserver: 'int', postgres: 'integer', sqlite: 'INTEGER', oracle: 'NUMBER(10)' }, nullable: false, defaultValue: '3600' },
      { name: 'AuthorizationCodeLifetime', type: 'integer', typeByEngine: { sqlserver: 'int', postgres: 'integer', sqlite: 'INTEGER', oracle: 'NUMBER(10)' }, nullable: false, defaultValue: '300' },
      { name: 'Created', type: 'timestamp', typeByEngine: { sqlserver: 'datetime2', postgres: 'timestamp with time zone', sqlite: 'TEXT', oracle: 'TIMESTAMP WITH TIME ZONE' }, nullable: false },
      { name: 'Updated', type: 'timestamp', typeByEngine: { sqlserver: 'datetime2', postgres: 'timestamp with time zone', sqlite: 'TEXT', oracle: 'TIMESTAMP WITH TIME ZONE' }, nullable: true }
    ],
    indexes: [
      { name: 'IX_Clients_ClientId', tableName: 'Clients', columns: ['ClientId'], isUnique: true }
    ],
    foreignKeys: []
  },
  {
    name: 'ClientGrantTypes',
    category: 'openiddict',
    categoryLabel: 'Klienci i Zakresy OIDC',
    description: 'Dozwolone typy nadań tokenów dla klienta (authorization_code, client_credentials itp.)',
    columns: [
      { name: 'Id', type: 'integer', typeByEngine: { sqlserver: 'int IDENTITY(1,1)', postgres: 'serial', sqlite: 'INTEGER PRIMARY KEY AUTOINCREMENT', oracle: 'NUMBER GENERATED BY DEFAULT AS IDENTITY' }, nullable: false, isPrimaryKey: true, isAutoIncrement: true },
      { name: 'ClientId', type: 'integer', typeByEngine: { sqlserver: 'int', postgres: 'integer', sqlite: 'INTEGER', oracle: 'NUMBER(10)' }, nullable: false },
      { name: 'GrantType', type: 'varchar(250)', typeByEngine: { sqlserver: 'nvarchar(250)', postgres: 'varchar(250)', sqlite: 'TEXT', oracle: 'VARCHAR2(250)' }, nullable: false }
    ],
    indexes: [
      { name: 'IX_ClientGrantTypes_ClientId', tableName: 'ClientGrantTypes', columns: ['ClientId'] }
    ],
    foreignKeys: [
      { name: 'FK_ClientGrantTypes_Clients_ClientId', tableName: 'ClientGrantTypes', column: 'ClientId', principalTable: 'Clients', principalColumn: 'Id', onDelete: 'CASCADE' }
    ]
  },
  {
    name: 'ClientRedirectUris',
    category: 'openiddict',
    categoryLabel: 'Klienci i Zakresy OIDC',
    description: 'Biała lista adresów przekierowań OIDC (Redirect URIs) dla klienta',
    columns: [
      { name: 'Id', type: 'integer', typeByEngine: { sqlserver: 'int IDENTITY(1,1)', postgres: 'serial', sqlite: 'INTEGER PRIMARY KEY AUTOINCREMENT', oracle: 'NUMBER GENERATED BY DEFAULT AS IDENTITY' }, nullable: false, isPrimaryKey: true, isAutoIncrement: true },
      { name: 'ClientId', type: 'integer', typeByEngine: { sqlserver: 'int', postgres: 'integer', sqlite: 'INTEGER', oracle: 'NUMBER(10)' }, nullable: false },
      { name: 'RedirectUri', type: 'varchar(2000)', typeByEngine: { sqlserver: 'nvarchar(2000)', postgres: 'varchar(2000)', sqlite: 'TEXT', oracle: 'VARCHAR2(2000)' }, nullable: false }
    ],
    indexes: [
      { name: 'IX_ClientRedirectUris_ClientId', tableName: 'ClientRedirectUris', columns: ['ClientId'] }
    ],
    foreignKeys: [
      { name: 'FK_ClientRedirectUris_Clients_ClientId', tableName: 'ClientRedirectUris', column: 'ClientId', principalTable: 'Clients', principalColumn: 'Id', onDelete: 'CASCADE' }
    ]
  },
  {
    name: 'ClientScopes',
    category: 'openiddict',
    categoryLabel: 'Klienci i Zakresy OIDC',
    description: 'Dozwolone zakresy uprawnień przydzielone do klienta',
    columns: [
      { name: 'Id', type: 'integer', typeByEngine: { sqlserver: 'int IDENTITY(1,1)', postgres: 'serial', sqlite: 'INTEGER PRIMARY KEY AUTOINCREMENT', oracle: 'NUMBER GENERATED BY DEFAULT AS IDENTITY' }, nullable: false, isPrimaryKey: true, isAutoIncrement: true },
      { name: 'ClientId', type: 'integer', typeByEngine: { sqlserver: 'int', postgres: 'integer', sqlite: 'INTEGER', oracle: 'NUMBER(10)' }, nullable: false },
      { name: 'Scope', type: 'varchar(200)', typeByEngine: { sqlserver: 'nvarchar(200)', postgres: 'varchar(200)', sqlite: 'TEXT', oracle: 'VARCHAR2(200)' }, nullable: false }
    ],
    indexes: [
      { name: 'IX_ClientScopes_ClientId', tableName: 'ClientScopes', columns: ['ClientId'] }
    ],
    foreignKeys: [
      { name: 'FK_ClientScopes_Clients_ClientId', tableName: 'ClientScopes', column: 'ClientId', principalTable: 'Clients', principalColumn: 'Id', onDelete: 'CASCADE' }
    ]
  },
  {
    name: 'ClientSecrets',
    category: 'openiddict',
    categoryLabel: 'Klienci i Zakresy OIDC',
    description: 'Haszowane sekrety uwierzytelniające klientów Poufnych (Confidential)',
    columns: [
      { name: 'Id', type: 'integer', typeByEngine: { sqlserver: 'int IDENTITY(1,1)', postgres: 'serial', sqlite: 'INTEGER PRIMARY KEY AUTOINCREMENT', oracle: 'NUMBER GENERATED BY DEFAULT AS IDENTITY' }, nullable: false, isPrimaryKey: true, isAutoIncrement: true },
      { name: 'ClientId', type: 'integer', typeByEngine: { sqlserver: 'int', postgres: 'integer', sqlite: 'INTEGER', oracle: 'NUMBER(10)' }, nullable: false },
      { name: 'Description', type: 'varchar(2000)', typeByEngine: { sqlserver: 'nvarchar(2000)', postgres: 'varchar(2000)', sqlite: 'TEXT', oracle: 'VARCHAR2(2000)' }, nullable: true },
      { name: 'Value', type: 'varchar(max)', typeByEngine: { sqlserver: 'nvarchar(max)', postgres: 'text', sqlite: 'TEXT', oracle: 'CLOB' }, nullable: false },
      { name: 'Expiration', type: 'timestamp', typeByEngine: { sqlserver: 'datetime2', postgres: 'timestamp with time zone', sqlite: 'TEXT', oracle: 'TIMESTAMP WITH TIME ZONE' }, nullable: true },
      { name: 'Type', type: 'varchar(250)', typeByEngine: { sqlserver: 'nvarchar(250)', postgres: 'varchar(250)', sqlite: 'TEXT', oracle: 'VARCHAR2(250)' }, nullable: false, defaultValue: "'SharedSecret'" },
      { name: 'Created', type: 'timestamp', typeByEngine: { sqlserver: 'datetime2', postgres: 'timestamp with time zone', sqlite: 'TEXT', oracle: 'TIMESTAMP WITH TIME ZONE' }, nullable: false }
    ],
    indexes: [
      { name: 'IX_ClientSecrets_ClientId', tableName: 'ClientSecrets', columns: ['ClientId'] }
    ],
    foreignKeys: [
      { name: 'FK_ClientSecrets_Clients_ClientId', tableName: 'ClientSecrets', column: 'ClientId', principalTable: 'Clients', principalColumn: 'Id', onDelete: 'CASCADE' }
    ]
  },
  {
    name: 'ApiScopes',
    category: 'openiddict',
    categoryLabel: 'Klienci i Zakresy OIDC',
    description: 'Rejestr zakresów API w systemie (np. quorum.api, telemetry.read)',
    columns: [
      { name: 'Id', type: 'integer', typeByEngine: { sqlserver: 'int IDENTITY(1,1)', postgres: 'serial', sqlite: 'INTEGER PRIMARY KEY AUTOINCREMENT', oracle: 'NUMBER GENERATED BY DEFAULT AS IDENTITY' }, nullable: false, isPrimaryKey: true, isAutoIncrement: true },
      { name: 'Name', type: 'varchar(200)', typeByEngine: { sqlserver: 'nvarchar(200)', postgres: 'varchar(200)', sqlite: 'TEXT', oracle: 'VARCHAR2(200)' }, nullable: false },
      { name: 'DisplayName', type: 'varchar(200)', typeByEngine: { sqlserver: 'nvarchar(200)', postgres: 'varchar(200)', sqlite: 'TEXT', oracle: 'VARCHAR2(200)' }, nullable: true },
      { name: 'Description', type: 'varchar(1000)', typeByEngine: { sqlserver: 'nvarchar(1000)', postgres: 'varchar(1000)', sqlite: 'TEXT', oracle: 'VARCHAR2(1000)' }, nullable: true },
      { name: 'Required', type: 'boolean', typeByEngine: { sqlserver: 'bit', postgres: 'boolean', sqlite: 'INTEGER', oracle: 'NUMBER(1)' }, nullable: false, defaultValue: '0' },
      { name: 'Emphasize', type: 'boolean', typeByEngine: { sqlserver: 'bit', postgres: 'boolean', sqlite: 'INTEGER', oracle: 'NUMBER(1)' }, nullable: false, defaultValue: '0' },
      { name: 'ShowInDiscoveryDocument', type: 'boolean', typeByEngine: { sqlserver: 'bit', postgres: 'boolean', sqlite: 'INTEGER', oracle: 'NUMBER(1)' }, nullable: false, defaultValue: '1' },
      { name: 'Enabled', type: 'boolean', typeByEngine: { sqlserver: 'bit', postgres: 'boolean', sqlite: 'INTEGER', oracle: 'NUMBER(1)' }, nullable: false, defaultValue: '1' }
    ],
    indexes: [
      { name: 'IX_ApiScopes_Name', tableName: 'ApiScopes', columns: ['Name'], isUnique: true }
    ],
    foreignKeys: []
  },
  {
    name: 'IdentityResources',
    category: 'openiddict',
    categoryLabel: 'Klienci i Zakresy OIDC',
    description: 'Zasoby tożsamości OIDC (openid, profile, email, address, phone)',
    columns: [
      { name: 'Id', type: 'integer', typeByEngine: { sqlserver: 'int IDENTITY(1,1)', postgres: 'serial', sqlite: 'INTEGER PRIMARY KEY AUTOINCREMENT', oracle: 'NUMBER GENERATED BY DEFAULT AS IDENTITY' }, nullable: false, isPrimaryKey: true, isAutoIncrement: true },
      { name: 'Name', type: 'varchar(200)', typeByEngine: { sqlserver: 'nvarchar(200)', postgres: 'varchar(200)', sqlite: 'TEXT', oracle: 'VARCHAR2(200)' }, nullable: false },
      { name: 'DisplayName', type: 'varchar(200)', typeByEngine: { sqlserver: 'nvarchar(200)', postgres: 'varchar(200)', sqlite: 'TEXT', oracle: 'VARCHAR2(200)' }, nullable: true },
      { name: 'Description', type: 'varchar(1000)', typeByEngine: { sqlserver: 'nvarchar(1000)', postgres: 'varchar(1000)', sqlite: 'TEXT', oracle: 'VARCHAR2(1000)' }, nullable: true },
      { name: 'Enabled', type: 'boolean', typeByEngine: { sqlserver: 'bit', postgres: 'boolean', sqlite: 'INTEGER', oracle: 'NUMBER(1)' }, nullable: false, defaultValue: '1' },
      { name: 'Required', type: 'boolean', typeByEngine: { sqlserver: 'bit', postgres: 'boolean', sqlite: 'INTEGER', oracle: 'NUMBER(1)' }, nullable: false, defaultValue: '0' },
      { name: 'Emphasize', type: 'boolean', typeByEngine: { sqlserver: 'bit', postgres: 'boolean', sqlite: 'INTEGER', oracle: 'NUMBER(1)' }, nullable: false, defaultValue: '0' },
      { name: 'ShowInDiscoveryDocument', type: 'boolean', typeByEngine: { sqlserver: 'bit', postgres: 'boolean', sqlite: 'INTEGER', oracle: 'NUMBER(1)' }, nullable: false, defaultValue: '1' },
      { name: 'Created', type: 'timestamp', typeByEngine: { sqlserver: 'datetime2', postgres: 'timestamp with time zone', sqlite: 'TEXT', oracle: 'TIMESTAMP WITH TIME ZONE' }, nullable: false }
    ],
    indexes: [
      { name: 'IX_IdentityResources_Name', tableName: 'IdentityResources', columns: ['Name'], isUnique: true }
    ],
    foreignKeys: []
  },

  // --- 4. Open.IdentityServer Operacyjne (Persisted Grants & Klucze) ---
  {
    name: 'PersistedGrants',
    category: 'grants',
    categoryLabel: 'Aktywne Sesje i Klucze OIDC',
    description: 'Trwałe granty, refresh tokeny oraz zgody użytkowników w magazynie tokenów',
    columns: [
      { name: 'Key', type: 'varchar(200)', typeByEngine: { sqlserver: 'nvarchar(200)', postgres: 'varchar(200)', sqlite: 'TEXT PRIMARY KEY', oracle: 'VARCHAR2(200) PRIMARY KEY' }, nullable: false, isPrimaryKey: true },
      { name: 'Type', type: 'varchar(50)', typeByEngine: { sqlserver: 'nvarchar(50)', postgres: 'varchar(50)', sqlite: 'TEXT', oracle: 'VARCHAR2(50)' }, nullable: false },
      { name: 'SubjectId', type: 'varchar(200)', typeByEngine: { sqlserver: 'nvarchar(200)', postgres: 'varchar(200)', sqlite: 'TEXT', oracle: 'VARCHAR2(200)' }, nullable: true },
      { name: 'SessionId', type: 'varchar(100)', typeByEngine: { sqlserver: 'nvarchar(100)', postgres: 'varchar(100)', sqlite: 'TEXT', oracle: 'VARCHAR2(100)' }, nullable: true },
      { name: 'ClientId', type: 'varchar(200)', typeByEngine: { sqlserver: 'nvarchar(200)', postgres: 'varchar(200)', sqlite: 'TEXT', oracle: 'VARCHAR2(200)' }, nullable: false },
      { name: 'Description', type: 'varchar(200)', typeByEngine: { sqlserver: 'nvarchar(200)', postgres: 'varchar(200)', sqlite: 'TEXT', oracle: 'VARCHAR2(200)' }, nullable: true },
      { name: 'CreationTime', type: 'timestamp', typeByEngine: { sqlserver: 'datetime2', postgres: 'timestamp with time zone', sqlite: 'TEXT', oracle: 'TIMESTAMP WITH TIME ZONE' }, nullable: false },
      { name: 'Expiration', type: 'timestamp', typeByEngine: { sqlserver: 'datetime2', postgres: 'timestamp with time zone', sqlite: 'TEXT', oracle: 'TIMESTAMP WITH TIME ZONE' }, nullable: true },
      { name: 'ConsumedTime', type: 'timestamp', typeByEngine: { sqlserver: 'datetime2', postgres: 'timestamp with time zone', sqlite: 'TEXT', oracle: 'TIMESTAMP WITH TIME ZONE' }, nullable: true },
      { name: 'Data', type: 'varchar(max)', typeByEngine: { sqlserver: 'nvarchar(max)', postgres: 'text', sqlite: 'TEXT', oracle: 'CLOB' }, nullable: false }
    ],
    indexes: [
      { name: 'IX_PersistedGrants_SubjectId_ClientId_Type', tableName: 'PersistedGrants', columns: ['SubjectId', 'ClientId', 'Type'] },
      { name: 'IX_PersistedGrants_Expiration', tableName: 'PersistedGrants', columns: ['Expiration'] }
    ],
    foreignKeys: []
  },
  {
    name: 'Keys',
    category: 'grants',
    categoryLabel: 'Aktywne Sesje i Klucze OIDC',
    description: 'Rotowane klucze kryptograficzne do podpisywania tokenów JWT (JWKS)',
    columns: [
      { name: 'Id', type: 'varchar(450)', typeByEngine: { sqlserver: 'nvarchar(450)', postgres: 'varchar(450)', sqlite: 'TEXT PRIMARY KEY', oracle: 'VARCHAR2(450) PRIMARY KEY' }, nullable: false, isPrimaryKey: true },
      { name: 'Version', type: 'integer', typeByEngine: { sqlserver: 'int', postgres: 'integer', sqlite: 'INTEGER', oracle: 'NUMBER(10)' }, nullable: false },
      { name: 'Created', type: 'timestamp', typeByEngine: { sqlserver: 'datetime2', postgres: 'timestamp with time zone', sqlite: 'TEXT', oracle: 'TIMESTAMP WITH TIME ZONE' }, nullable: false },
      { name: 'Use', type: 'varchar(450)', typeByEngine: { sqlserver: 'nvarchar(450)', postgres: 'varchar(450)', sqlite: 'TEXT', oracle: 'VARCHAR2(450)' }, nullable: true },
      { name: 'Algorithm', type: 'varchar(100)', typeByEngine: { sqlserver: 'nvarchar(100)', postgres: 'varchar(100)', sqlite: 'TEXT', oracle: 'VARCHAR2(100)' }, nullable: false },
      { name: 'IsX509Certificate', type: 'boolean', typeByEngine: { sqlserver: 'bit', postgres: 'boolean', sqlite: 'INTEGER', oracle: 'NUMBER(1)' }, nullable: false, defaultValue: '0' },
      { name: 'DataProtected', type: 'boolean', typeByEngine: { sqlserver: 'bit', postgres: 'boolean', sqlite: 'INTEGER', oracle: 'NUMBER(1)' }, nullable: false, defaultValue: '0' },
      { name: 'Data', type: 'varchar(max)', typeByEngine: { sqlserver: 'nvarchar(max)', postgres: 'text', sqlite: 'TEXT', oracle: 'CLOB' }, nullable: false }
    ],
    indexes: [
      { name: 'IX_Keys_Use', tableName: 'Keys', columns: ['Use'] }
    ],
    foreignKeys: []
  }
];
